name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm ci
      - name: Building Beatstars Trends
        run: npx nx run beatstars-trends:build
      - name: Archive Beatstars Trends Artifact
        uses: actions/upload-artifact@master
        with:
          name: beatstars-trends-artifact
          path: dist/apps/beatstars-trends/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: beatstars-trends-artifact
          path: apps/beatstars-trends/dist
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEATSTARS_TRENDS }}'
          channelId: live
          entryPoint: "./apps/beatstars-trends/"
          projectId: beatstars-trends
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
